### ISSUE TITLE
Error with other clients 

### ISSUE THREAD

**Issue by m3xicang0d** [NoSequel/TabAPI#4]
![image](https://user-images.githubusercontent.com/64879531/135943032-8c2cdf81-79af-4cbb-aac8-eb16898215bf.png)
If I use a client like "Cosmic Client" the tab appears in red ..

**Comment by NoSequel** [comment]
This is because of the ping value being -1 by default to remove ping from tab on Lunar Client, you could set the ping value to 0. There's a method in the TabElement class to set the ping value (TabElement#add(x, y, text, ping).
